In [1]:
# ques 1
import numpy as np

mat1=np.empty((3,3))
mat2=np.empty((3,3))
print("enter the elements of first matrix:")
for i in range(0,3):
    for j in range(0,3):
        mat1[i][j]=int(input(f"enter element {i},{j} of matrix1:"))
        mat2[i][j]=int(input(f"enter element {i},{j} of matrix2:"))
print(f"matrix1\n {mat1}")
print(f"matrix2 \n {mat2}")

enter the elements of first matrix:
matrix1
 [[ 2.  5.  8.]
 [ 2.  4. 56.]
 [ 9.  9.  8.]]
matrix2 
 [[ 3.  7. 10.]
 [70. 87.  0.]
 [ 7. 45. 67.]]


In [2]:
transpose=np.transpose(mat1)
print(f"transpose is: \n {transpose}")

transpose is: 
 [[ 2.  2.  9.]
 [ 5.  4.  9.]
 [ 8. 56.  8.]]


In [3]:
print("direct multiplication:")
print(mat1 * mat2)
print("matrix multiplication:")
print(np.dot(mat1,mat2))

direct multiplication:
[[  6.  35.  80.]
 [140. 348.   0.]
 [ 63. 405. 536.]]
matrix multiplication:
[[ 412.  809.  556.]
 [ 678. 2882. 3772.]
 [ 713. 1206.  626.]]


In [4]:
print(f"diangonal sum: {np.trace(mat2)}")

diangonal sum: 157.0


In [5]:
print(f"determinant is :{np.linalg.det(mat1)}")

determinant is :1352.0000000000005


In [6]:
print(f"inverse is : \n {np.linalg.inv(mat1)}")

inverse is : 
 [[-0.34911243  0.02366864  0.18343195]
 [ 0.36094675 -0.04142012 -0.07100592]
 [-0.01331361  0.01997041 -0.00147929]]


In [7]:
print(f"rank is : \n {np.linalg.matrix_rank(mat1)}")

rank is : 
 3


In [8]:
print(f"eigen values: \n {np.linalg.eig(mat1).eigenvalues}")

eigen values: 
 [ 31.92682951  -2.79932725 -15.12750226]


In [9]:
print(f"eigen vectors: \n {np.linalg.eig(mat1).eigenvectors}")

eigen vectors: 
 [[-0.25831961 -0.66441138  0.12656861]
 [-0.86817417  0.74438901 -0.94008465]
 [-0.42372702 -0.06665217  0.31657739]]
