In [6]:
# ques 1
import numpy as np
from numpy import random

f=np.array((-40,30,32,23))
c=(f-32)*(5/9)
print(c)

[-40.          -1.11111111   0.          -5.        ]


In [3]:
# ques 2

arr = random.randint(100,size=(1000))
variance = np.var(arr)
mean= np.mean(arr)
standard_deviation= np.std(arr)
print(f"Mean is {mean}\n Varience is {variance}\n Standard deviation is {standard_deviation}")

Mean is 50.733
 Varience is 797.5657110000001
 Standard deviation is 28.241205905555805


In [4]:
# ques 3
angles=random.randint(360,size=(5))
radians=np.radians(angles)
print(angles)
print(radians)

[196 291  92 146 164]
[3.42084533 5.07890812 1.60570291 2.54818071 2.86233997]


In [5]:
# ques 4
arr=random.randint(20,size=(5))
difference=np.diff(arr)
print(arr)
print(difference)

[12  3  1 12 14]
[-9 -2 11  2]


In [6]:
# ques 5
arr=np.array([1+2j,3-1j,1-5j,3-2j,12-7j])
sort=np.sort_complex(arr)
print(arr)
print(sort)

[ 1.+2.j  3.-1.j  1.-5.j  3.-2.j 12.-7.j]
[ 1.-5.j  1.+2.j  3.-2.j  3.-1.j 12.-7.j]


In [7]:
# ques 6
arr=random.randint(0,20,size=(5))
print(arr)
print([x for x in arr if x>4])

[ 2  6  3 13  5]
[np.int32(6), np.int32(13), np.int32(5)]


In [ ]:
# ques 7
arr=random.randint(0,20,size=(5))
print(arr)
k=int(input("enter a num to search:"))
found=0
for i in range(0,5):
    if arr[i]==k:
        print(f"number found at {i}")
        found=1
if found==0:
    print("not found")

[12  1  3  5  1]
number found at 1
number found at 4


In [12]:
# ques 8
arr=np.array([2,3,6,1,6,9])
np.savetxt("num.txt",arr)
loaded=np.loadtxt("num.txt")
print(f"the loaded text is {loaded}")

the loaded text is [2. 3. 6. 1. 6. 9.]


In [13]:
# ques 9
evenarr=np.arange(30,61,2)
print(evenarr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [14]:
# ques 10
arr=random.randint(1,8,size=(3,3))
print(arr)
all_sum=np.sum(arr)
col_sum=np.sum(arr,axis=0)
row_sum=np.sum(arr,axis=1)
print(f"all sum: {all_sum}")
print(f"col sum: {col_sum}")
print(f"row sum : {row_sum}")

[[5 2 3]
 [3 6 3]
 [3 4 2]]
all sum: 31
col sum: [11 12  8]
row sum : [10 12  9]
