In [2]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.7 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/12.8 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.8 MB 1.9 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.8 MB 1.9 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.8 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.8 MB 1.4 MB/s eta 0:00:08
   --------- ------


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

#to create display and check the type of a numpy array
p=np.array((1,2,3,4,5))
print(p)
print(type(p))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#to create a numpy array of numbers from 2 to 10 with diff 2 and print it
a=np.arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [8]:
# to create an array of zeroes

p=np.zeros(10,int)
print(p)

[0 0 0 0 0 0 0 0 0 0]


In [9]:
## to create an array of zeroes

p=np.ones(10)
print(p)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#To create a 3×3 matrix (2D array) filled with 1s, where each element is an integer, and then print it.

p=np.ones((3,3),int)
print(p)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
# To create a 3×3 NumPy matrix (2D array) with specific values that you provide, and print it.

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# To create and display a 3×3 identity matrix using NumPy’s np.eye() function.

identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
