In [5]:
# To create a NumPy array of numbers from 2 to 7.
#To demonstrate array slicing (selecting parts of an array).

import numpy as np
arr=np.arange(2,8)
print(arr)
print (arr[1:5])
print(arr[:5])
print(arr[3:])
print(arr[-4:-1])
print(arr[-1:-4:-1])


[2 3 4 5 6 7]
[3 4 5 6]
[2 3 4 5 6]
[5 6 7]
[4 5 6]
[7 6 5]


In [6]:
# To show what happens when you assign one array to another in NumPy and then modify one of them.
# It demonstrates that arr2 is not a copy, it shares the same data with arr1.

arr1=np.arange(2,10)
arr2=arr1
arr2[2]=10
print(arr1)
print(arr2)

[ 2  3 10  5  6  7  8  9]
[ 2  3 10  5  6  7  8  9]


In [7]:
# To show how to create an independent copy of a NumPy array.
# To demonstrate that modifying the copy does NOT affect the original array.

arr1=np.arange(2,10)
arr2=np.copy(arr1)
arr2[2]=10
print(arr1)
print(arr2)

[2 3 4 5 6 7 8 9]
[ 2  3 10  5  6  7  8  9]


In [12]:
# To create two separate NumPy arrays a and b.
# To join (concatenate) them into a single array c.

arr1=np.arange(2,10)
arr2=np.arange(11,20)
print(arr1,arr2)
arr3=np.concatenate((arr1,arr2))
print(arr3)

[2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [13]:
# To create two 2D arrays (matrices) of different shapes.
# To show how to concatenate 2D arrays along columns using axis=1.

matrix1=np.array(([1,2,3],[4,5,6]))
matrix2=np.array(([11,22],[44,55]))
print(matrix1)
print(matrix2)
matrix3=np.concatenate((matrix1,matrix2),axis=1)
print(matrix3)

[[1 2 3]
 [4 5 6]]
[[11 22]
 [44 55]]
[[ 1  2  3 11 22]
 [ 4  5  6 44 55]]


In [14]:
# To create two 2×2 matrices.
# To demonstrate vertical concatenation (default axis=0) and horizontal concatenation (axis=1).

mat1=np.array(([1,2],[4,5]))
mat2=np.array(([11,22],[44,55]))
mat3=np.concatenate((mat1,mat2))
print(mat3)
mat3=np.concatenate((mat1,mat2),axis=1)
print(mat3)

[[ 1  2]
 [ 4  5]
 [11 22]
 [44 55]]
[[ 1  2 11 22]
 [ 4  5 44 55]]


In [15]:
# To find positions (indices) of elements in a NumPy array that satisfy a condition.
# To show how to handle cases where no element satisfies the condition.

arr=np.array((4,6,6,7))
x=np.where(arr >= 6)
print(x[0])
x=np.where(arr == 6)
print(x[0])
x=np.where(arr == 9)
if(x[0].size >= 1):
    print(x[0])
else:
    print("not found")

[1 2 3]
[1 2]
not found
